spring:
  profiles:
    active: dev
---
spring:
  profiles: dev
zuul:
  ignored-services: '*'
  ignoredPatterns: /**/api/**
  routes:
    account-service: /account/**
    payment-service: /payment/**
    inventory-service: /inventory/**
    order-service: /order/**
    user-service: /user/**
    catalog-service: /catalog/**
    shopping-cart-service: /shoppingcart/**
security:
  oauth2:
    resource:
      userInfoUri: http://localhost:8181/auth/user
  ignored: /catalog/**
eureka:
  instance:
    prefer-ip-address: true
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/