spring:
  profiles:
    active: dev
---
spring:
  profiles: dev
  jpa:
    properties:
      hibernate:
        hbm2ddl:
          auto: update
    # disable open EntityManager in View
    open-in-view: false
  datasource:
    url: jdbc:mysql://localhost:3306/time_store_account?useUnicode=true&characterEncoding=utf-8
    username: time
    password: 123456
    driver-class-name: com.mysql.jdbc.Driver
security:
  oauth2:
    resource:
      userInfoUri: http://localhost:8181/auth/user
    client:
      client-id: timeyang
      access-token-uri: http://localhost:8787
eureka:
  instance:
    prefer-ip-address: true
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/